name: approve-pr
needs: int-test
runs-on: ubuntu-latest
steps:
  - name: Checkout project
    uses: actions/checkout@v3

  - name: Aprovando Pull Request
    run: |
      gh pr review $PR_NUMBER --approve