name: eslint
runs-on: ubuntu-latest
steps:
  - name: Pass
    run: echo "pass"
  # - name: Checkout project
  #   uses: actions/checkout@v3

  # - name: Set up Node.js
  #   uses: actions/setup-node@v3
  #   with:
  #     node-version: 16

  # - name: Install dependencies
  #   run: npm install

  # - name: Run eslint
  #   run: npm run lint