name: lock-pr
needs: [eslint, unit-test, int-test, request-changes-pr]
runs-on: ubuntu-latest
steps:
  - name: Checkout project
    uses: actions/checkout@v3

  - name: Bloqueando Pull Request
    run: |
      if ! gh pr lock $PR_NUMBER; then
        exit 0
      fi