name: request-changes-pr
needs: [eslint, unit-test, int-test]
env:
  ESLINT_STATUS: ${{ needs.eslint.result }}
  UNIT_STATUS: ${{ needs.unit-test.result }}
  INT_STATUS: ${{ needs.int-test.result }}
runs-on: ubuntu-latest
if: ${{ failure() }}
steps:
  - name: Checkout project
    uses: actions/checkout@v3

  - name: Requisitando mudanças ao Pull Request
    run: |
      if [[ $ESLINT_STATUS == 'failure' ]]; then
        gh pr review $PR_NUMBER --request-changes --body "Necessário corrigir os problemas com lint."
      fi
      if [[ $UNIT_STATUS == 'failure' ]]; then
        gh pr review $PR_NUMBER --request-changes --body "Necessário corrigir os testes unitários."
      fi
      if [[ $INT_STATUS == 'failure' ]]; then
        gh pr review $PR_NUMBER --request-changes --body "Necessário corrigir os testes de integração."