name: Executando testes unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  # schedule:
  #   - cron: '0 7 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test:unit

      - name: Set up status check
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            gh pr check "${GITHUB_SHA}" --status "completed" --conclusion "success" --name "Tests" --title "Tests Passed" --message "All tests passed successfully."
          else
            gh pr check "${GITHUB_SHA}" --status "completed" --conclusion "failure" --name "Tests" --title "Tests Failed" --message "Some tests failed. Please check the test results."
          fi