name: Merge feito com a Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types:
        - closed

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'

      - name: Montar a build
        run: npm run build

      - name: Fazer deploy
        run: |
          echo "Fazendo deploy ..."

      - name: Done
        run: |
          echo "done!"