name: Development Merge

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types:
        - closed
  pull_request_target:
    types:
      - closed

jobs:

  deploy-stg:
    runs-on: ubuntu-latest

    steps:

      - name: Build project
        run: echo "npm run build ..."

      - name: Fazer deploy
        run: |
          echo "Fazendo deploy ..."

      - name: Done
        run: |
          echo "done!"