name: Development Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - development

jobs:

  deploy-stg:
    runs-on: ubuntu-latest

    steps:

      - name: Build project
        run: echo "npm run build ..."

      - name: Deploy
        run: |
          echo "deploy hml..."

      - name: Done
        run: |
          echo "done!"