name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Pass
        run: echo "pass"
      # - name: Checkout project
      #   uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: Install dependencies
      #   run: npm install

      # - name: Run eslint
      #   run: npm run lint

  unit-test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  int-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run int tests
        run: npm run test:int

  approve-pr:
    needs: [int-test]
    runs-on: ubuntu-latest
    steps:
      - name: Aprovando Pull Request
        run: |
          gh pr review $PR_NUMBER --approve

  unlock-pr:
    needs: [approve-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Desbloqueando Pull Request
        run: |
          gh pr unlock $PR_NUMBER

  request-changes-pr:
    needs: [eslint, unit-test, int-test]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Requisitando mudanças ao Pull Request
        run: |
          gh pr review $PR_NUMBER --request-changes --body "Necessário corrigir os testes."

  lock-pr:
    needs: [request-changes-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Bloqueando Pull Request
        run: |
          
          if ! gh pr lock $PR_NUMBER; then
            exit 0
          fi