name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
    # types:
    #     - opened
  # schedule:
  #   - cron: '0 7 * * *'

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Aprovando Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr review $PR_NUMBER --comment -b "Todos os testes passaram"
          gh pr review $PR_NUMBER --approve

      # - name: Bloqueando o pull request
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #   run: |
      #     echo "Blocking merge PR..."
      #     gh pr lock $PR_NUMBER
      #     # gh pr lock $PR_NUMBER
      #     # gh pr label $PR_NUMBER --add block-merge

      # - name: Verificar status dos testes
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #     JOB_STATUS: "${{ job.status }}"
      #   run: |
      #     if [ '$JOB_STATUS' == 'failure' ]; then
      #       echo 'Os testes falharam. O pull request será bloqueado.'
      #       gh pr lock $PR_NUMBER
      #       gh pr review $PR_NUMBER --comment -b "Necessário verificar testes"
      #       gh pr review $PR_NUMBER --request-changes
      #       exit 1
      #     fi
      #     if [ '$JOB_STATUS' == 'success' ]; then
      #       echo "Os testes passaram. O pull request será liberado."
      #       gh pr unlock $PR_NUMBER
      #       gh pr review $PR_NUMBER --comment -b "Todos os testes passaram"
      #       gh pr review $PR_NUMBER --approve
      #       exit 1
      #     fi