name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  # schedule:
  #   - cron: '0 7 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

      - name: Bloqueando o pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Blocking merge PR..."
          gh pr lock ${{ github.event.pull_request.number }}

      # - name: Verificar status dos testes
      #   run: |
      #     if [ ${{ job.status }} == 'failure' ]; then
      #       echo "Os testes falharam. O pull request será bloqueado."
      #       exit 1
      #     fi