name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - locked
      - unlocked
      - synchronize
  pull_request_target:
    types:
      - opened
      - reopened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

  unit-test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  int-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run int tests
        run: npm run test:int

  approve-pr:
    needs: int-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Approving Pull Request
        run: |
          gh pr review $PR_NUMBER --approve

  unlock-pr:
    needs: approve-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Unlocking Pull Request
        run: |
          gh pr unlock $PR_NUMBER

  request-changes-pr:
    needs: [eslint, unit-test, int-test]
    env:
      ESLINT_STATUS: ${{ needs.eslint.result }}
      UNIT_STATUS: ${{ needs.unit-test.result }}
      INT_STATUS: ${{ needs.int-test.result }}
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Requesting changes to the Pull Request
        run: |
          if [[ $ESLINT_STATUS == 'failure' ]]; then
            gh pr review $PR_NUMBER --request-changes --body "ESLINT :: Necessário corrigir os problemas com lint."
          fi
          if [[ $UNIT_STATUS == 'failure' ]]; then
            gh pr review $PR_NUMBER --request-changes --body "TESTES UNITÁRIOS :: Necessário corrigir os testes unitários."
          fi
          if [[ $INT_STATUS == 'failure' ]]; then
            gh pr review $PR_NUMBER --request-changes --body "ESTES DE INTEGRAÇÃO :: Necessário corrigir os testes de integração."
          fi

  lock-pr:
    needs: [eslint, unit-test, int-test, request-changes-pr]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Blocking Pull Request
        run: |
          if ! gh pr lock $PR_NUMBER; then
            exit 0
          fi