name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  - include: ./on-pull-request/eslint.yml
  - include: ./on-pull-request/unit-test.yml
  - include: ./on-pull-request/int-test.yml
  - include: ./on-pull-request/approve-pr.yml
  - include: ./on-pull-request/approve-pr.yml
  - include: ./on-pull-request/lock-pr.yml
  - include: ./on-pull-request/unlock-pr.yml