name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

  unit-test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: |
          if ! npm run test:unit; then
            echo "tests-failed::true" >> $GITHUB_ENV
            exit 0
          else
            echo "tests-failed::false" >> $GITHUB_ENV
          fi

  approve-pr:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ env.tests-failed == 'false' && needs.unit-test.result == 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Aprovando Pull Request
        run: |
          gh pr review $PR_NUMBER --approve

  unlock-pr:
    needs: approve-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Desbloqueando Pull Request
        run: |
          gh pr unlock $PR_NUMBER

  request-changes-pr:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ env.tests-failed == 'true' || needs.unit-test.result != 'success' || needs.unit-test.result == 'failure'  || needs.unit-test.status == 'failure' || needs.unit-test.conclusion != 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Requisitando mudanças ao Pull Request
        run: |
          gh pr review $PR_NUMBER --request-changes --body "Please make necessary changes."

  lock-pr:
    needs: request-changes-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Bloqueando Pull Request
        run: |
          
          if ! gh pr lock $PR_NUMBER; then
            exit 0
          fi
