name: Validação - Testes Unitários

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

  unit-test:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  approve-pr:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ needs.unit-test.result == 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Aprovando Pull Request
        run: |
          gh pr review $PR_NUMBER --comment -b "Todos os testes passaram"
          gh pr review $PR_NUMBER --approve

  request-changes-pr:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ needs.unit-test.result != 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Requisitando mudanças ao Pull Request
        run: |
          gh pr review $PR_NUMBER --request-changes --body "Please make necessary changes."


  unlock-pr:
    needs: approve-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Desbloqueando Pull Request
        run: |
          gh pr unlock $PR_NUMBER


  lock-pr:
    needs: request-changes-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Bloqueando Pull Request
        run: |
          gh pr lock $PR_NUMBER
